Repository cygnan/twitter-wordcloud-bot, pull requests merged in 2018-03, with the labels that each got.

#75 Add missing configuration to #14
  app.json
Labels: deployment

#14 Add deploy to heroku button
  README.md
  app.json
Labels: deployment, work in progress

#85 Remove matplotlib from requirements.in
  requirements.in
  requirements.txt
Labels: refactoring

#89 Update README.md
  README.md
Labels: docs

#91 Update the description in app.json
  app.json
Labels: deployment

#90 Fix typo in README.md
  README.md
Labels: docs

#93 Fix a small typo on README.md
  README.md
Labels: docs
